# Generated by Django 5.2.4 on 2025-07-20 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('pricing', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('freemium', 'Freemium'), ('open_source', 'Open Source')], default='free', max_length=50)),
                ('website_url', models.URLField(max_length=500)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('listing_type', models.CharField(choices=[('simple', 'Simple'), ('verified', 'Verified'), ('featured', 'Featured')], default='simple', max_length=50)),
                ('tags', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('contact_company', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_website', models.URLField(max_length=500)),
                ('tool_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=200)),
                ('owner_company', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_method', models.CharField(choices=[('email', 'Email Verification'), ('domain', 'Domain Verification'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=100)),
                ('removal_reason', models.CharField(choices=[('discontinued', 'Tool Discontinued'), ('rebranding', 'Rebranding'), ('privacy', 'Privacy Concerns'), ('inaccurate', 'Inaccurate Information'), ('other', 'Other')], max_length=100)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tool_removal_requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ToolSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_website', models.URLField(max_length=500)),
                ('tool_category', models.CharField(max_length=100)),
                ('tool_pricing', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('freemium', 'Freemium'), ('open_source', 'Open Source')], max_length=50)),
                ('tool_description', models.TextField()),
                ('tool_detailed_description', models.TextField(blank=True, null=True)),
                ('tool_features', models.TextField(blank=True, null=True)),
                ('tool_tags', models.TextField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('simple', 'Simple'), ('verified', 'Verified'), ('featured', 'Featured')], default='simple', max_length=50)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_company', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tool_submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
